# Generated by Django 3.1.6 on 2021-04-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0002_newuser_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
