# Generated by Django 3.1.6 on 2021-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210408_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='teams_left',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams_left', to='main.Team'),
        ),
    ]
