# Generated by Django 3.1.6 on 2021-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210413_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='servers',
            field=models.ManyToManyField(blank=True, null=True, to='main.Server'),
        ),
    ]
